<?php

return [
    [
        'slug' => 'the-fillmore',
        'display_name' => 'The Fillmore',
        'aliases' => ['Fillmore', 'Fillmore Auditorium'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'theatre',
        'capacity_estimate' => 1315,
        'prestige_weight' => 1.00,
        'activity_weight' => 1.00,
        'source_priority_default' => 90,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.thefillmore.com/shows',
        'adapter_class' => 'PanicBooking\\EventSync\\Adapters\\FillmoreAdapter',
        'is_core_venue' => true,
        'has_official_sync' => true,
        'notoriety_multiplier' => 1.15,
    ],
    [
        'slug' => 'bill-graham-civic-auditorium',
        'display_name' => 'Bill Graham Civic Auditorium',
        'aliases' => ['Bill Graham', 'BGCA', 'Bill Graham Civic'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'auditorium',
        'capacity_estimate' => 8500,
        'prestige_weight' => 1.00,
        'activity_weight' => 1.00,
        'source_priority_default' => 85,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.ticketmaster.com/bill-graham-civic-auditorium-tickets-san-francisco/venue/229531',
        'adapter_class' => 'PanicBooking\\EventSync\\Adapters\\TicketmasterAdapter',
        'ticketmaster_venue_id' => 'KovZpaKope',
        'is_core_venue' => true,
        'has_official_sync' => true,
        'notoriety_multiplier' => 1.15,
    ],
    [
        'slug' => 'the-warfield',
        'display_name' => 'The Warfield',
        'aliases' => ['Warfield', 'Warfield Theatre'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'theatre',
        'capacity_estimate' => 2300,
        'prestige_weight' => 0.98,
        'activity_weight' => 1.00,
        'source_priority_default' => 90,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.thewarfieldtheatre.com/events',
        'adapter_class' => 'PanicBooking\\EventSync\\Adapters\\WarfieldAdapter',
        'is_core_venue' => true,
        'has_official_sync' => true,
        'notoriety_multiplier' => 1.12,
    ],
    [
        'slug' => 'great-american-music-hall',
        'display_name' => 'Great American Music Hall',
        'aliases' => ['GAMH', 'Great American'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'hall',
        'capacity_estimate' => 470,
        'prestige_weight' => 0.88,
        'activity_weight' => 0.95,
        'source_priority_default' => 88,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://gamh.com/calendar/',
        'adapter_class' => 'PanicBooking\\EventSync\\Adapters\\GamhAdapter',
        'is_core_venue' => true,
        'has_official_sync' => true,
        'notoriety_multiplier' => 1.08,
    ],
    [
        'slug' => 'regency-ballroom',
        'display_name' => 'Regency Ballroom',
        'aliases' => ['The Regency Ballroom', 'Regency'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'ballroom',
        'capacity_estimate' => 1400,
        'prestige_weight' => 0.85,
        'activity_weight' => 0.95,
        'source_priority_default' => 88,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://theregencyballroom.com/shows/',
        'adapter_class' => 'PanicBooking\\EventSync\\Adapters\\RegencyAdapter',
        'is_core_venue' => true,
        'has_official_sync' => true,
        'notoriety_multiplier' => 1.08,
    ],
    [
        'slug' => 'the-independent',
        'display_name' => 'The Independent',
        'aliases' => ['Independent', 'The Indy'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 500,
        'prestige_weight' => 0.80,
        'activity_weight' => 0.95,
        'source_priority_default' => 80,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.theindependentsf.com/',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.05,
    ],
    [
        'slug' => 'august-hall',
        'display_name' => 'August Hall',
        'aliases' => ['August Hall SF'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'hall',
        'capacity_estimate' => 1000,
        'prestige_weight' => 0.72,
        'activity_weight' => 0.90,
        'source_priority_default' => 78,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.augusthallsf.com/events/',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.00,
    ],
    [
        'slug' => 'the-chapel',
        'display_name' => 'The Chapel',
        'aliases' => ['Chapel SF', 'The Chapel SF'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 500,
        'prestige_weight' => 0.78,
        'activity_weight' => 0.95,
        'source_priority_default' => 78,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://thechapelsf.com/calendar/',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.03,
    ],
    [
        'slug' => 'cafe-du-nord',
        'display_name' => 'Cafe du Nord',
        'aliases' => ['Café du Nord', 'Cafe Du Nord'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 300,
        'prestige_weight' => 0.70,
        'activity_weight' => 0.90,
        'source_priority_default' => 76,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://cafedunord.com/',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.00,
    ],
    [
        'slug' => 'rickshaw-stop',
        'display_name' => 'Rickshaw Stop',
        'aliases' => ['Rickshaw'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 400,
        'prestige_weight' => 0.74,
        'activity_weight' => 0.92,
        'source_priority_default' => 76,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://rickshawstop.com/',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.01,
    ],
    [
        'slug' => 'bottom-of-the-hill',
        'display_name' => 'Bottom of the Hill',
        'aliases' => ['Bottom Of The Hill', 'BOTH'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 250,
        'prestige_weight' => 0.75,
        'activity_weight' => 0.90,
        'source_priority_default' => 76,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.bottomofthehill.com/calendar.html',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.04,
    ],
    [
        'slug' => 'bimbos-365-club',
        'display_name' => "Bimbo's 365 Club",
        'aliases' => ['Bimbos 365 Club', 'Bimbos'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 685,
        'prestige_weight' => 0.76,
        'activity_weight' => 0.85,
        'source_priority_default' => 75,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.bimbos365club.com/events',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.02,
    ],
    [
        'slug' => 'brick-and-mortar-music-hall',
        'display_name' => 'Brick & Mortar Music Hall',
        'aliases' => ['Brick and Mortar', 'Brick & Mortar'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'club',
        'capacity_estimate' => 350,
        'prestige_weight' => 0.68,
        'activity_weight' => 0.88,
        'source_priority_default' => 74,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.brickandmortarmusic.com/events',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.00,
    ],
    [
        'slug' => 'palace-of-fine-arts-theatre',
        'display_name' => 'Palace of Fine Arts Theatre',
        'aliases' => ['Palace of Fine Arts', 'Palace of Fine Arts Theater'],
        'city' => 'San Francisco',
        'state' => 'CA',
        'venue_type' => 'theatre',
        'capacity_estimate' => 962,
        'prestige_weight' => 0.82,
        'activity_weight' => 0.70,
        'source_priority_default' => 72,
        'sync_enabled' => true,
        'official_calendar_url' => 'https://www.palaceoffinearts.org/what-s-on',
        'adapter_class' => null,
        'is_core_venue' => true,
        'has_official_sync' => false,
        'notoriety_multiplier' => 1.05,
    ],
];
